LOCAL_SRCS += \
    $(GET_LOCAL_DIR)/sanitizer_common/sancov_flags.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_allocator.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_common.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_common_libcdep.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_coverage_libcdep_new.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_coverage_win_dll_thunk.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_coverage_win_dynamic_runtime_thunk.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_coverage_win_sections.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_coverage_win_weak_interception.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_deadlock_detector1.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_deadlock_detector2.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_errno.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_file.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_flag_parser.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_flags.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_fuchsia.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_libc.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_libignore.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_linux.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_linux_libcdep.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_linux_s390.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_mac.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_mac_libcdep.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_persistent_allocator.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_platform_limits_linux.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_platform_limits_posix.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_posix.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_posix_libcdep.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_printf.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_procmaps_common.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_procmaps_freebsd.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_procmaps_linux.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_procmaps_mac.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_stackdepot.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_stacktrace.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_stacktrace_libcdep.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_stoptheworld_linux_libcdep.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_stoptheworld_mac.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_suppressions.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_symbolizer.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_symbolizer_fuchsia.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_symbolizer_libbacktrace.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_symbolizer_libcdep.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_symbolizer_mac.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_symbolizer_posix_libcdep.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_symbolizer_win.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_thread_registry.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_tls_get_addr.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_unwind_linux_libcdep.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_win.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_win_dll_thunk.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_win_dynamic_runtime_thunk.cc \
    $(GET_LOCAL_DIR)/sanitizer_common/sanitizer_win_weak_interception.cc \
    $(GET_LOCAL_DIR)/scudo/scudo_allocator.cpp \
    $(GET_LOCAL_DIR)/scudo/scudo_crc32.cpp \
    $(GET_LOCAL_DIR)/scudo/scudo_flags.cpp \
    $(GET_LOCAL_DIR)/scudo/scudo_wrapper.cpp \
    $(GET_LOCAL_DIR)/scudo/scudo_termination.cpp \
    $(GET_LOCAL_DIR)/scudo/scudo_tls_android.cpp \
    $(GET_LOCAL_DIR)/scudo/scudo_tls_fuchsia.cpp \
    $(GET_LOCAL_DIR)/scudo/scudo_tls_linux.cpp \
    $(GET_LOCAL_DIR)/scudo/scudo_utils.cpp \

LOCAL_COMPILEFLAGS += -I$(GET_LOCAL_DIR) -Wno-error=conversion


